slug = "its-not-a-phase-mommy-pig"
title = "ITS NOT A PHASE MOMMY PIG"
author = "Aarin"
value = 40
description = """[Peppa](peppasdoublelife.doc) has been a really unruly little pig lately, but she won't tell us why! Those rebellious teenagers, you know? Can you find out what's going on with her? Wrap your answer to the question in `flag{...}` and submit as all lowercase with underscores for spaces."""
tags = [ "file" ]
files = ["peppasdoublelife.doc"]
flag = "flag{millie_b}"
enabled = true
