slug = "who-am-i"
title = "Who Am I?????"
author = "Aarin"
value = 10
description = """[This guy](whatsmyname.png) doesn't know his name. Dang. Maybe if someone taught him how to read he would... Submit the flag as flag{name} where `name` is the first name of the person, all lowercase."""
tags = [ "file" ]
files = ["whatsmyname.png"]
flag = "flag{jared}"
enabled = true
