slug = "a-simple-catch"
title = "A Simple Catch"
author = "Peter"
value = 5
description = """[This](warmup.pcapng) is a warmup problem for you to get familiar with Wireshark!"""
tags = [ "packet" ]
files = ["warmup.pcapng"]
flag = "flag{always_trust_the_lock}"
enabled = false