slug = "too-medium"
title = "TOO MEDIUM!"
author = "Henry"
value = 20
description = """Uh oh! The stranger caught onto your eavesdropping, but he still refuses to get off the network and is now encrypting [messages](too_medium.pcapng)! Maybe his friend can give you a hint?"""
tags = [ "packet" ]
files = ["too_medium.pcapng"]
flag = "flag{I_<3_cake_popsss}"
enabled = true
