slug = "cookie-monster"
title = "COOKIE MONSTER!"
author = "Henry"
value = 10
description = """GIVE ME MY COOKIES! COOKIESSSSSS! Hint: You might want to look into base-64 encoding. [file](cookie_monster.pcapng)"""
tags = [ "packet" ]
files = ["cookie_monster.pcapng"]
flag = "flag{i_am_but_a_smol_island}"
enabled = true