slug = "feedback-file-analysis"
title = "Feedback for File Analysis Workshop"
author = "jeffrey"
value = 5
description = """Hello, kind stranger! Get free points for giving us feedback on our workshop! https://forms.gle/9179pC5XbbBVxKgg6"""
tags = [ "feedback" ]
files = []
flag = "flag{hidd3n_messAg3s_everYwher3}"
enabled = true
