slug = "feedback-file-analysis"
title = "File Analysis Workshop Feedback"
author = "jeffrey"
value = 5
description = """Hello, kind stranger! Get free points for giving us [feedback](https://forms.gle/9179pC5XbbBVxKgg6) on our workshop!"""
tags = [ "feedback" ]
files = []
flag = "flag{hidd3n_messAg3s_everYwher3}"
enabled = true
