id = 1
title = "Fall General Meeting"
short = "Fall GM" 
date = "Week 1 Wednesday 10/7 6:30-8:30PM PDT"
description = """Dip your toes <small>(or fully submerge, we won’t judge)</small> into the world of Cybersecurity by attending our <strong>Fall GM!</strong> We’ll go over what ACM Cyber is all about--and why you should totally be a part of our amazing, <span role="img" aria-label="sparkle">✨</span>beginner-friendly<span role="img" aria-label="sparkle">✨</span> cybersecurity club. And we have some fun challenges prepared that might make your brain cry but in a good way, we promise. They’re also <strong>Avatar: The Last Airbender</strong> themed, because we love you and want you to have fun.

Zoom link will be posted on the Facebook Event, the ACM Membership Portal, and in our Discord announcement near the start of the event!"""
link = """[Facebook Event](https://www.facebook.com/events/2688605051393645/)"""
slides = """"""