slug = "MEOWgic-bytes"
title = "Meow-gic Bytes"
author = "Yunfan"
value = 15
description = """Woosh. Magic cat has stolen your flag, and it looks like he scratched up the image it's saved in. Can you defeat his wizardry and recover the file?"""
tags = [ "" ]
files = [cat.jpg]
flag = "flag{th3_gre4t_c4tsby}"
enabled = false