slug = "MEOWgic-bytes"
title = "Meow-gic Bytes"
author = "Yunfan"
value = 30
description = """Woosh. Magic cat has stolen your flag, and it looks like he scratched up the image it's hidden in. Can you defeat his wizardry and recover the flag?"""
tags = [ "file" ]
files = [ "cat.png" ]
flag = "flag{th3_gre4t_c4tsby}"
enabled = true