slug = "the-jedi-archives"
title = "The Jedi Archives"
author = "Peter"
value = 20
description = """Master Kenobi has been looking for a file in the archives, but he can't seem to find it. Can you help him?"""
tags = [ "packet" ]
files = ["FTP.pcapng"]
flag = "flag{kamino_is_missing}"
enabled = false